// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serializeProtoClass.proto

package com.homework.entity;

public final class SerializeProtoClassOuterClass {
  private SerializeProtoClassOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerializeProtoClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.SerializeProtoClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 integer = 1;</code>
     */
    int getInteger();

    /**
     * <code>string string = 2;</code>
     */
    java.lang.String getString();
    /**
     * <code>string string = 2;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    boolean hasInnerClass();
    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    com.homework.entity.SerializeProtoClassOuterClass.InnerClass getInnerClass();
    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getInnerClassOrBuilder();

    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass> 
        getListInnerClassesList();
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    com.homework.entity.SerializeProtoClassOuterClass.InnerClass getListInnerClasses(int index);
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    int getListInnerClassesCount();
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    java.util.List<? extends com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> 
        getListInnerClassesOrBuilderList();
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getListInnerClassesOrBuilder(
        int index);

    /**
     * <code>repeated string setStrings = 5;</code>
     */
    java.util.List<java.lang.String>
        getSetStringsList();
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    int getSetStringsCount();
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    java.lang.String getSetStrings(int index);
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    com.google.protobuf.ByteString
        getSetStringsBytes(int index);

    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */
    int getMapCount();
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */
    boolean containsMap(
        java.lang.String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMap();
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapMap();
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    java.lang.String getMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code protobuf.SerializeProtoClass}
   */
  public  static final class SerializeProtoClass extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.SerializeProtoClass)
      SerializeProtoClassOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SerializeProtoClass.newBuilder() to construct.
    private SerializeProtoClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializeProtoClass() {
      integer_ = 0;
      string_ = "";
      listInnerClasses_ = java.util.Collections.emptyList();
      setStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SerializeProtoClass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              integer_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              string_ = s;
              break;
            }
            case 26: {
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder subBuilder = null;
              if (innerClass_ != null) {
                subBuilder = innerClass_.toBuilder();
              }
              innerClass_ = input.readMessage(com.homework.entity.SerializeProtoClassOuterClass.InnerClass.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(innerClass_);
                innerClass_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                listInnerClasses_ = new java.util.ArrayList<com.homework.entity.SerializeProtoClassOuterClass.InnerClass>();
                mutable_bitField0_ |= 0x00000008;
              }
              listInnerClasses_.add(
                  input.readMessage(com.homework.entity.SerializeProtoClassOuterClass.InnerClass.parser(), extensionRegistry));
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                setStrings_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              setStrings_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          listInnerClasses_ = java.util.Collections.unmodifiableList(listInnerClasses_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          setStrings_ = setStrings_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.class, com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.Builder.class);
    }

    private int bitField0_;
    public static final int INTEGER_FIELD_NUMBER = 1;
    private int integer_;
    /**
     * <code>int32 integer = 1;</code>
     */
    public int getInteger() {
      return integer_;
    }

    public static final int STRING_FIELD_NUMBER = 2;
    private volatile java.lang.Object string_;
    /**
     * <code>string string = 2;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      }
    }
    /**
     * <code>string string = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INNERCLASS_FIELD_NUMBER = 3;
    private com.homework.entity.SerializeProtoClassOuterClass.InnerClass innerClass_;
    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    public boolean hasInnerClass() {
      return innerClass_ != null;
    }
    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getInnerClass() {
      return innerClass_ == null ? com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance() : innerClass_;
    }
    /**
     * <code>.protobuf.InnerClass innerClass = 3;</code>
     */
    public com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getInnerClassOrBuilder() {
      return getInnerClass();
    }

    public static final int LISTINNERCLASSES_FIELD_NUMBER = 4;
    private java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass> listInnerClasses_;
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    public java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass> getListInnerClassesList() {
      return listInnerClasses_;
    }
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    public java.util.List<? extends com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> 
        getListInnerClassesOrBuilderList() {
      return listInnerClasses_;
    }
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    public int getListInnerClassesCount() {
      return listInnerClasses_.size();
    }
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getListInnerClasses(int index) {
      return listInnerClasses_.get(index);
    }
    /**
     * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
     */
    public com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getListInnerClassesOrBuilder(
        int index) {
      return listInnerClasses_.get(index);
    }

    public static final int SETSTRINGS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList setStrings_;
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSetStringsList() {
      return setStrings_;
    }
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    public int getSetStringsCount() {
      return setStrings_.size();
    }
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    public java.lang.String getSetStrings(int index) {
      return setStrings_.get(index);
    }
    /**
     * <code>repeated string setStrings = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSetStringsBytes(int index) {
      return setStrings_.getByteString(index);
    }

    public static final int MAP_FIELD_NUMBER = 6;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_MapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    public java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map = 6;</code>
     */

    public java.lang.String getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (integer_ != 0) {
        output.writeInt32(1, integer_);
      }
      if (!getStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, string_);
      }
      if (innerClass_ != null) {
        output.writeMessage(3, getInnerClass());
      }
      for (int i = 0; i < listInnerClasses_.size(); i++) {
        output.writeMessage(4, listInnerClasses_.get(i));
      }
      for (int i = 0; i < setStrings_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, setStrings_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (integer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, integer_);
      }
      if (!getStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, string_);
      }
      if (innerClass_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getInnerClass());
      }
      for (int i = 0; i < listInnerClasses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, listInnerClasses_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < setStrings_.size(); i++) {
          dataSize += computeStringSizeNoTag(setStrings_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSetStringsList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, map__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass)) {
        return super.equals(obj);
      }
      com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass other = (com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass) obj;

      boolean result = true;
      result = result && (getInteger()
          == other.getInteger());
      result = result && getString()
          .equals(other.getString());
      result = result && (hasInnerClass() == other.hasInnerClass());
      if (hasInnerClass()) {
        result = result && getInnerClass()
            .equals(other.getInnerClass());
      }
      result = result && getListInnerClassesList()
          .equals(other.getListInnerClassesList());
      result = result && getSetStringsList()
          .equals(other.getSetStringsList());
      result = result && internalGetMap().equals(
          other.internalGetMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INTEGER_FIELD_NUMBER;
      hash = (53 * hash) + getInteger();
      hash = (37 * hash) + STRING_FIELD_NUMBER;
      hash = (53 * hash) + getString().hashCode();
      if (hasInnerClass()) {
        hash = (37 * hash) + INNERCLASS_FIELD_NUMBER;
        hash = (53 * hash) + getInnerClass().hashCode();
      }
      if (getListInnerClassesCount() > 0) {
        hash = (37 * hash) + LISTINNERCLASSES_FIELD_NUMBER;
        hash = (53 * hash) + getListInnerClassesList().hashCode();
      }
      if (getSetStringsCount() > 0) {
        hash = (37 * hash) + SETSTRINGS_FIELD_NUMBER;
        hash = (53 * hash) + getSetStringsList().hashCode();
      }
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.SerializeProtoClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.SerializeProtoClass)
        com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.class, com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.Builder.class);
      }

      // Construct using com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListInnerClassesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        integer_ = 0;

        string_ = "";

        if (innerClassBuilder_ == null) {
          innerClass_ = null;
        } else {
          innerClass_ = null;
          innerClassBuilder_ = null;
        }
        if (listInnerClassesBuilder_ == null) {
          listInnerClasses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          listInnerClassesBuilder_.clear();
        }
        setStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_SerializeProtoClass_descriptor;
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass getDefaultInstanceForType() {
        return com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.getDefaultInstance();
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass build() {
        com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass buildPartial() {
        com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass result = new com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.integer_ = integer_;
        result.string_ = string_;
        if (innerClassBuilder_ == null) {
          result.innerClass_ = innerClass_;
        } else {
          result.innerClass_ = innerClassBuilder_.build();
        }
        if (listInnerClassesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            listInnerClasses_ = java.util.Collections.unmodifiableList(listInnerClasses_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.listInnerClasses_ = listInnerClasses_;
        } else {
          result.listInnerClasses_ = listInnerClassesBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          setStrings_ = setStrings_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.setStrings_ = setStrings_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass) {
          return mergeFrom((com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass other) {
        if (other == com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass.getDefaultInstance()) return this;
        if (other.getInteger() != 0) {
          setInteger(other.getInteger());
        }
        if (!other.getString().isEmpty()) {
          string_ = other.string_;
          onChanged();
        }
        if (other.hasInnerClass()) {
          mergeInnerClass(other.getInnerClass());
        }
        if (listInnerClassesBuilder_ == null) {
          if (!other.listInnerClasses_.isEmpty()) {
            if (listInnerClasses_.isEmpty()) {
              listInnerClasses_ = other.listInnerClasses_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureListInnerClassesIsMutable();
              listInnerClasses_.addAll(other.listInnerClasses_);
            }
            onChanged();
          }
        } else {
          if (!other.listInnerClasses_.isEmpty()) {
            if (listInnerClassesBuilder_.isEmpty()) {
              listInnerClassesBuilder_.dispose();
              listInnerClassesBuilder_ = null;
              listInnerClasses_ = other.listInnerClasses_;
              bitField0_ = (bitField0_ & ~0x00000008);
              listInnerClassesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListInnerClassesFieldBuilder() : null;
            } else {
              listInnerClassesBuilder_.addAllMessages(other.listInnerClasses_);
            }
          }
        }
        if (!other.setStrings_.isEmpty()) {
          if (setStrings_.isEmpty()) {
            setStrings_ = other.setStrings_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSetStringsIsMutable();
            setStrings_.addAll(other.setStrings_);
          }
          onChanged();
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int integer_ ;
      /**
       * <code>int32 integer = 1;</code>
       */
      public int getInteger() {
        return integer_;
      }
      /**
       * <code>int32 integer = 1;</code>
       */
      public Builder setInteger(int value) {
        
        integer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 integer = 1;</code>
       */
      public Builder clearInteger() {
        
        integer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object string_ = "";
      /**
       * <code>string string = 2;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = string_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string = 2;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string = 2;</code>
       */
      public Builder clearString() {
        
        string_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>string string = 2;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string_ = value;
        onChanged();
        return this;
      }

      private com.homework.entity.SerializeProtoClassOuterClass.InnerClass innerClass_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> innerClassBuilder_;
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public boolean hasInnerClass() {
        return innerClassBuilder_ != null || innerClass_ != null;
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getInnerClass() {
        if (innerClassBuilder_ == null) {
          return innerClass_ == null ? com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance() : innerClass_;
        } else {
          return innerClassBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public Builder setInnerClass(com.homework.entity.SerializeProtoClassOuterClass.InnerClass value) {
        if (innerClassBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          innerClass_ = value;
          onChanged();
        } else {
          innerClassBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public Builder setInnerClass(
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder builderForValue) {
        if (innerClassBuilder_ == null) {
          innerClass_ = builderForValue.build();
          onChanged();
        } else {
          innerClassBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public Builder mergeInnerClass(com.homework.entity.SerializeProtoClassOuterClass.InnerClass value) {
        if (innerClassBuilder_ == null) {
          if (innerClass_ != null) {
            innerClass_ =
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass.newBuilder(innerClass_).mergeFrom(value).buildPartial();
          } else {
            innerClass_ = value;
          }
          onChanged();
        } else {
          innerClassBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public Builder clearInnerClass() {
        if (innerClassBuilder_ == null) {
          innerClass_ = null;
          onChanged();
        } else {
          innerClass_ = null;
          innerClassBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder getInnerClassBuilder() {
        
        onChanged();
        return getInnerClassFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getInnerClassOrBuilder() {
        if (innerClassBuilder_ != null) {
          return innerClassBuilder_.getMessageOrBuilder();
        } else {
          return innerClass_ == null ?
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance() : innerClass_;
        }
      }
      /**
       * <code>.protobuf.InnerClass innerClass = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> 
          getInnerClassFieldBuilder() {
        if (innerClassBuilder_ == null) {
          innerClassBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder>(
                  getInnerClass(),
                  getParentForChildren(),
                  isClean());
          innerClass_ = null;
        }
        return innerClassBuilder_;
      }

      private java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass> listInnerClasses_ =
        java.util.Collections.emptyList();
      private void ensureListInnerClassesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          listInnerClasses_ = new java.util.ArrayList<com.homework.entity.SerializeProtoClassOuterClass.InnerClass>(listInnerClasses_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> listInnerClassesBuilder_;

      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass> getListInnerClassesList() {
        if (listInnerClassesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listInnerClasses_);
        } else {
          return listInnerClassesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public int getListInnerClassesCount() {
        if (listInnerClassesBuilder_ == null) {
          return listInnerClasses_.size();
        } else {
          return listInnerClassesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getListInnerClasses(int index) {
        if (listInnerClassesBuilder_ == null) {
          return listInnerClasses_.get(index);
        } else {
          return listInnerClassesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder setListInnerClasses(
          int index, com.homework.entity.SerializeProtoClassOuterClass.InnerClass value) {
        if (listInnerClassesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListInnerClassesIsMutable();
          listInnerClasses_.set(index, value);
          onChanged();
        } else {
          listInnerClassesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder setListInnerClasses(
          int index, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder builderForValue) {
        if (listInnerClassesBuilder_ == null) {
          ensureListInnerClassesIsMutable();
          listInnerClasses_.set(index, builderForValue.build());
          onChanged();
        } else {
          listInnerClassesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder addListInnerClasses(com.homework.entity.SerializeProtoClassOuterClass.InnerClass value) {
        if (listInnerClassesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListInnerClassesIsMutable();
          listInnerClasses_.add(value);
          onChanged();
        } else {
          listInnerClassesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder addListInnerClasses(
          int index, com.homework.entity.SerializeProtoClassOuterClass.InnerClass value) {
        if (listInnerClassesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListInnerClassesIsMutable();
          listInnerClasses_.add(index, value);
          onChanged();
        } else {
          listInnerClassesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder addListInnerClasses(
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder builderForValue) {
        if (listInnerClassesBuilder_ == null) {
          ensureListInnerClassesIsMutable();
          listInnerClasses_.add(builderForValue.build());
          onChanged();
        } else {
          listInnerClassesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder addListInnerClasses(
          int index, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder builderForValue) {
        if (listInnerClassesBuilder_ == null) {
          ensureListInnerClassesIsMutable();
          listInnerClasses_.add(index, builderForValue.build());
          onChanged();
        } else {
          listInnerClassesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder addAllListInnerClasses(
          java.lang.Iterable<? extends com.homework.entity.SerializeProtoClassOuterClass.InnerClass> values) {
        if (listInnerClassesBuilder_ == null) {
          ensureListInnerClassesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listInnerClasses_);
          onChanged();
        } else {
          listInnerClassesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder clearListInnerClasses() {
        if (listInnerClassesBuilder_ == null) {
          listInnerClasses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          listInnerClassesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public Builder removeListInnerClasses(int index) {
        if (listInnerClassesBuilder_ == null) {
          ensureListInnerClassesIsMutable();
          listInnerClasses_.remove(index);
          onChanged();
        } else {
          listInnerClassesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder getListInnerClassesBuilder(
          int index) {
        return getListInnerClassesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder getListInnerClassesOrBuilder(
          int index) {
        if (listInnerClassesBuilder_ == null) {
          return listInnerClasses_.get(index);  } else {
          return listInnerClassesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public java.util.List<? extends com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> 
           getListInnerClassesOrBuilderList() {
        if (listInnerClassesBuilder_ != null) {
          return listInnerClassesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listInnerClasses_);
        }
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder addListInnerClassesBuilder() {
        return getListInnerClassesFieldBuilder().addBuilder(
            com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder addListInnerClassesBuilder(
          int index) {
        return getListInnerClassesFieldBuilder().addBuilder(
            index, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.InnerClass listInnerClasses = 4;</code>
       */
      public java.util.List<com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder> 
           getListInnerClassesBuilderList() {
        return getListInnerClassesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder> 
          getListInnerClassesFieldBuilder() {
        if (listInnerClassesBuilder_ == null) {
          listInnerClassesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder, com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder>(
                  listInnerClasses_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          listInnerClasses_ = null;
        }
        return listInnerClassesBuilder_;
      }

      private com.google.protobuf.LazyStringList setStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSetStringsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          setStrings_ = new com.google.protobuf.LazyStringArrayList(setStrings_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSetStringsList() {
        return setStrings_.getUnmodifiableView();
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public int getSetStringsCount() {
        return setStrings_.size();
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public java.lang.String getSetStrings(int index) {
        return setStrings_.get(index);
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSetStringsBytes(int index) {
        return setStrings_.getByteString(index);
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public Builder setSetStrings(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSetStringsIsMutable();
        setStrings_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public Builder addSetStrings(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSetStringsIsMutable();
        setStrings_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public Builder addAllSetStrings(
          java.lang.Iterable<java.lang.String> values) {
        ensureSetStringsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, setStrings_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public Builder clearSetStrings() {
        setStrings_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string setStrings = 5;</code>
       */
      public Builder addSetStringsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSetStringsIsMutable();
        setStrings_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> map_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public boolean containsMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMap() {
        return getMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public java.lang.String getMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public java.lang.String getMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public Builder removeMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */
      public Builder putMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 6;</code>
       */

      public Builder putAllMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.SerializeProtoClass)
    }

    // @@protoc_insertion_point(class_scope:protobuf.SerializeProtoClass)
    private static final com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass();
    }

    public static com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializeProtoClass>
        PARSER = new com.google.protobuf.AbstractParser<SerializeProtoClass>() {
      @java.lang.Override
      public SerializeProtoClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SerializeProtoClass(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SerializeProtoClass> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializeProtoClass> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.homework.entity.SerializeProtoClassOuterClass.SerializeProtoClass getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InnerClassOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.InnerClass)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string string = 1;</code>
     */
    java.lang.String getString();
    /**
     * <code>string string = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringBytes();

    /**
     * <code>string string1 = 2;</code>
     */
    java.lang.String getString1();
    /**
     * <code>string string1 = 2;</code>
     */
    com.google.protobuf.ByteString
        getString1Bytes();
  }
  /**
   * Protobuf type {@code protobuf.InnerClass}
   */
  public  static final class InnerClass extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.InnerClass)
      InnerClassOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InnerClass.newBuilder() to construct.
    private InnerClass(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InnerClass() {
      string_ = "";
      string1_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InnerClass(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              string_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              string1_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_InnerClass_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_InnerClass_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.homework.entity.SerializeProtoClassOuterClass.InnerClass.class, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder.class);
    }

    public static final int STRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object string_;
    /**
     * <code>string string = 1;</code>
     */
    public java.lang.String getString() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string_ = s;
        return s;
      }
    }
    /**
     * <code>string string = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringBytes() {
      java.lang.Object ref = string_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRING1_FIELD_NUMBER = 2;
    private volatile java.lang.Object string1_;
    /**
     * <code>string string1 = 2;</code>
     */
    public java.lang.String getString1() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string1_ = s;
        return s;
      }
    }
    /**
     * <code>string string1 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getString1Bytes() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, string_);
      }
      if (!getString1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, string1_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, string_);
      }
      if (!getString1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, string1_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.homework.entity.SerializeProtoClassOuterClass.InnerClass)) {
        return super.equals(obj);
      }
      com.homework.entity.SerializeProtoClassOuterClass.InnerClass other = (com.homework.entity.SerializeProtoClassOuterClass.InnerClass) obj;

      boolean result = true;
      result = result && getString()
          .equals(other.getString());
      result = result && getString1()
          .equals(other.getString1());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRING_FIELD_NUMBER;
      hash = (53 * hash) + getString().hashCode();
      hash = (37 * hash) + STRING1_FIELD_NUMBER;
      hash = (53 * hash) + getString1().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.homework.entity.SerializeProtoClassOuterClass.InnerClass prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.InnerClass}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.InnerClass)
        com.homework.entity.SerializeProtoClassOuterClass.InnerClassOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_InnerClass_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_InnerClass_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.homework.entity.SerializeProtoClassOuterClass.InnerClass.class, com.homework.entity.SerializeProtoClassOuterClass.InnerClass.Builder.class);
      }

      // Construct using com.homework.entity.SerializeProtoClassOuterClass.InnerClass.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        string_ = "";

        string1_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.homework.entity.SerializeProtoClassOuterClass.internal_static_protobuf_InnerClass_descriptor;
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getDefaultInstanceForType() {
        return com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance();
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass build() {
        com.homework.entity.SerializeProtoClassOuterClass.InnerClass result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.homework.entity.SerializeProtoClassOuterClass.InnerClass buildPartial() {
        com.homework.entity.SerializeProtoClassOuterClass.InnerClass result = new com.homework.entity.SerializeProtoClassOuterClass.InnerClass(this);
        result.string_ = string_;
        result.string1_ = string1_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.homework.entity.SerializeProtoClassOuterClass.InnerClass) {
          return mergeFrom((com.homework.entity.SerializeProtoClassOuterClass.InnerClass)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.homework.entity.SerializeProtoClassOuterClass.InnerClass other) {
        if (other == com.homework.entity.SerializeProtoClassOuterClass.InnerClass.getDefaultInstance()) return this;
        if (!other.getString().isEmpty()) {
          string_ = other.string_;
          onChanged();
        }
        if (!other.getString1().isEmpty()) {
          string1_ = other.string1_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.homework.entity.SerializeProtoClassOuterClass.InnerClass parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.homework.entity.SerializeProtoClassOuterClass.InnerClass) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object string_ = "";
      /**
       * <code>string string = 1;</code>
       */
      public java.lang.String getString() {
        java.lang.Object ref = string_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringBytes() {
        java.lang.Object ref = string_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder setString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder clearString() {
        
        string_ = getDefaultInstance().getString();
        onChanged();
        return this;
      }
      /**
       * <code>string string = 1;</code>
       */
      public Builder setStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object string1_ = "";
      /**
       * <code>string string1 = 2;</code>
       */
      public java.lang.String getString1() {
        java.lang.Object ref = string1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string1 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getString1Bytes() {
        java.lang.Object ref = string1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string1 = 2;</code>
       */
      public Builder setString1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 2;</code>
       */
      public Builder clearString1() {
        
        string1_ = getDefaultInstance().getString1();
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 2;</code>
       */
      public Builder setString1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string1_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.InnerClass)
    }

    // @@protoc_insertion_point(class_scope:protobuf.InnerClass)
    private static final com.homework.entity.SerializeProtoClassOuterClass.InnerClass DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.homework.entity.SerializeProtoClassOuterClass.InnerClass();
    }

    public static com.homework.entity.SerializeProtoClassOuterClass.InnerClass getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InnerClass>
        PARSER = new com.google.protobuf.AbstractParser<InnerClass>() {
      @java.lang.Override
      public InnerClass parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerClass(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InnerClass> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InnerClass> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.homework.entity.SerializeProtoClassOuterClass.InnerClass getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_SerializeProtoClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_SerializeProtoClass_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_SerializeProtoClass_MapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_SerializeProtoClass_MapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_InnerClass_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_InnerClass_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031serializeProtoClass.proto\022\010protobuf\"\205\002" +
      "\n\023SerializeProtoClass\022\017\n\007integer\030\001 \001(\005\022\016" +
      "\n\006string\030\002 \001(\t\022(\n\ninnerClass\030\003 \001(\0132\024.pro" +
      "tobuf.InnerClass\022.\n\020listInnerClasses\030\004 \003" +
      "(\0132\024.protobuf.InnerClass\022\022\n\nsetStrings\030\005" +
      " \003(\t\0223\n\003map\030\006 \003(\0132&.protobuf.SerializePr" +
      "otoClass.MapEntry\032*\n\010MapEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"-\n\nInnerClass\022\016\n\006s" +
      "tring\030\001 \001(\t\022\017\n\007string1\030\002 \001(\tB\025\n\023com.home" +
      "work.entityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_SerializeProtoClass_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_SerializeProtoClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_SerializeProtoClass_descriptor,
        new java.lang.String[] { "Integer", "String", "InnerClass", "ListInnerClasses", "SetStrings", "Map", });
    internal_static_protobuf_SerializeProtoClass_MapEntry_descriptor =
      internal_static_protobuf_SerializeProtoClass_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_SerializeProtoClass_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_SerializeProtoClass_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protobuf_InnerClass_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_InnerClass_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_InnerClass_descriptor,
        new java.lang.String[] { "String", "String1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
